/**
 * BlockLinkPreview automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {LinkPreview} from "./LinkPreview";

export interface BlockLinkPreview {
    link_preview?: LinkPreview
}

