/**
 * BlockImage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {FileObject} from "./FileObject";

export interface BlockImage extends Block {
    image?: FileObject
}

