/**
 * Block automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BlockBookmark} from "./BlockBookmark";
import {ParentId} from "./ParentId";
import {User} from "./User";

export interface Block {
    object?: string
    id?: string
    parent?: ParentId
    type?: string
    created_time?: string
    created_by?: User
    last_edited_time?: string
    last_edited_by?: User
    archived?: boolean
    in_trash?: boolean
    has_children?: boolean
}

