/**
 * BlockPDF automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {PDF} from "./PDF";

export interface BlockPDF extends Block {
    pdf?: PDF
}

