/**
 * Block automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Page} from "./Page";
import {User} from "./User";

export interface Block {
    object?: string
    id?: string
    parent?: Page
    created_time?: string
    last_edited_time?: string
    created_by?: User
    last_edited_by?: User
    has_children?: boolean
    in_trash?: boolean
    type?: string
}

