/**
 * BlockNumberedListItem automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {NumberedListItem} from "./NumberedListItem";

export interface BlockNumberedListItem extends Block {
    numbered_list_item?: NumberedListItem
}

