/**
 * BlockHeading3 automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";

export interface BlockHeading extends Block {
    heading_3?: BlockHeading
}

