/**
 * BlockQuote automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {Quote} from "./Quote";

export interface BlockQuote extends Block {
    quote?: Quote
}

