/**
 * BlockChildPage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {ChildPage} from "./ChildPage";

export interface BlockChildPage extends Block {
    child_page?: ChildPage
}

