/**
 * BlockFile automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {File} from "./File";

export interface BlockFile extends Block {
    file?: File
}

