/**
 * BlockChildDatabase automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {ChildDatabase} from "./ChildDatabase";

export interface BlockChildDatabase extends Block {
    child_database?: ChildDatabase
}

