/**
 * BlockBookmark automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {Bookmark} from "./Bookmark";

export interface BlockBookmark extends Block {
    bookmark?: Bookmark
}

