/**
 * BlockEquation automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {Equation} from "./Equation";

export interface BlockEquation extends Block {
    equation?: Equation
}

