/**
 * BlockBulletedListItem automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {BulletedListItem} from "./BulletedListItem";

export interface BlockBulletedListItem extends Block {
    bulleted_list_item?: BulletedListItem
}

