/**
 * BlockParagraph automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {Paragraph} from "./Paragraph";

export interface BlockParagraph extends Block {
    paragraph?: Paragraph
}

