/**
 * BlockCallout automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";
import {Callout} from "./Callout";

export interface BlockCallout extends Block {
    callout?: Callout
}

