/**
 * Bookmark automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {RichText} from "./RichText";

export interface Bookmark {
    caption?: Array<RichText>
    url?: string
}

