/**
 * BulletedListItem automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Block} from "./Block";

export interface BulletedListItem {
    rich_text?: Array<BulletedListItem>
    color?: string
    children?: Array<Block>
}

