/**
 * Callout automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {RichText} from "./RichText";
import {Icon} from "./Icon";

export interface Callout {
    rich_text?: Array<RichText>
    icon?: Icon
    color?: string
}

