/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {ClientAbstract, CredentialsInterface, TokenStoreInterface} from "sdkgen-client"
import {HttpBearer} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {UsersTag} from "./UsersTag";
import {DatabasesTag} from "./DatabasesTag";

export class Client extends ClientAbstract {
    public users(): UsersTag
    {
        return new UsersTag(
            this.httpClient,
            this.parser
        );
    }

    public databases(): DatabasesTag
    {
        return new DatabasesTag(
            this.httpClient,
            this.parser
        );
    }



    public static build(token: string): Client
    {
        return new Client('https://api.notion.com', new HttpBearer(token));
    }
}
