/**
 * Code automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {RichText} from "./RichText";

export interface Code {
    caption?: Array<RichText>
    rich_text?: Array<RichText>
    language?: string
}

