/**
 * Comment automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ParentId} from "./ParentId";
import {RichText} from "./RichText";

export interface Comment {
    parent?: ParentId
    discussion_id?: string
    rich_text?: RichText
}

