/**
 * Comment automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {PageId} from "./PageId";
import {RichText} from "./RichText";

export interface Comment {
    parent?: PageId
    discussion_id?: string
    rich_text?: RichText
}

