/**
 * DatabaseTitle automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {DatabaseAnnotations} from "./DatabaseAnnotations";
export interface DatabaseTitle {
    type?: string
    text?: string
    annotations?: DatabaseAnnotations
    plain_text?: string
    href?: string
}
