/**
 * DatabaseAnnotations automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DatabaseAnnotations {
    bold?: boolean
    italic?: boolean
    strikethrough?: boolean
    underline?: boolean
    code?: boolean
    color?: string
}
