/**
 * Database automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {DatabaseIcon} from "./DatabaseIcon";
import {DatabaseCover} from "./DatabaseCover";
import {DatabaseTitle} from "./DatabaseTitle";
export interface Database {
    object?: string
    id?: string
    created_time?: string
    last_edited_time?: string
    icon?: DatabaseIcon
    cover?: DatabaseCover
    url?: string
    title?: Array<DatabaseTitle>
    description?: Array<DatabaseTitle>
}
