/**
 * DatabaseParentId automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ParentId} from "./ParentId";

export interface DatabaseParentId extends ParentId {
    database_id?: string
}

