/**
 * EmojiIcon automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Icon} from "./Icon";

export interface EmojiIcon extends Icon {
    emoji?: string
}

