/**
 * ExternalIcon automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Icon} from "./Icon";
import {ExternalObject} from "./ExternalObject";

export interface ExternalIcon extends Icon {
    external?: ExternalObject
}

