/**
 * FileIcon automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Icon} from "./Icon";
import {File} from "./File";

export interface FileIcon extends Icon {
    file?: File
}

