/**
 * File automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {RichText} from "./RichText";
import {FileObject} from "./FileObject";

export interface File {
    caption?: Array<RichText>
    file?: FileObject
    name?: string
}

