/**
 * Heading automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {RichText} from "./RichText";

export interface Heading {
    rich_text?: Array<RichText>
    color?: string
    is_toggleable?: boolean
}

