/**
 * Icon automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {EmojiIcon} from "./EmojiIcon";
import {FileIcon} from "./FileIcon";
import {ExternalIcon} from "./ExternalIcon";

export interface Icon {
    type?: string
}

