/**
 * Page automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {User} from "./User";
import {FileObject} from "./FileObject";
import {Icon} from "./Icon";
import {ParentId} from "./ParentId";

export interface Page {
    object?: string
    id?: string
    created_time?: string
    last_edited_time?: string
    created_by?: User
    last_edited_by?: User
    cover?: FileObject
    icon?: Icon
    in_trash?: boolean
    properties?: Record<string, any>
    parent?: ParentId
    url?: string
    public_url?: string
}

