/**
 * Paragraph automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {RichText} from "./RichText";
import {Block} from "./Block";

export interface Paragraph {
    rich_text?: Array<RichText>
    color?: string
    children?: Array<Block>
}

