/**
 * ParentId automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {DatabaseParentId} from "./DatabaseParentId";
import {PageParentId} from "./PageParentId";
import {BlockParentId} from "./BlockParentId";
import {WorkspaceParentId} from "./WorkspaceParentId";

export interface ParentId {
    type?: string
}

