/**
 * PDF automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {PDFExternal} from "./PDFExternal";
import {PDFFile} from "./PDFFile";
import {RichText} from "./RichText";

export interface PDF {
    caption?: Array<RichText>
    type?: string
}

