/**
 * PDFExternal automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {PDF} from "./PDF";
import {ExternalObject} from "./ExternalObject";

export interface PDFExternal extends PDF {
    external?: ExternalObject
}

