/**
 * PDFFile automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {PDF} from "./PDF";
import {FileObject} from "./FileObject";

export interface PDFFile extends PDF {
    file?: FileObject
}

