/**
 * RichText automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {RichTextAnnotation} from "./RichTextAnnotation";

export interface RichText {
    type?: string
    annotations?: RichTextAnnotation
    plain_text?: string
    href?: string
}

