/**
 * RichTextText automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {RichText} from "./RichText";
import {Text} from "./Text";

export interface RichTextText extends RichText {
    text?: Text
}

