/**
 * RichTextEquation automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {RichText} from "./RichText";
import {Equation} from "./Equation";

export interface RichTextEquation extends RichText {
    equation?: Equation
}

