/**
 * Text automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Link} from "./Link";

export interface Text {
    content?: string
    link?: Link
}

