/**
 * UserTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {Error} from "./Error";
import {ErrorException} from "./ErrorException";
import {User} from "./User";
import {UserCollection} from "./UserCollection";

export class UserTag extends TagAbstract {
    /**
     * Returns a paginated list of Users for the workspace. The response may contain fewer than page_size of results.
     *
     * @returns {Promise<UserCollection>}
     * @throws {ErrorException}
     * @throws {ClientException}
     */
    public async getAll(startCursor?: string, pageSize?: number): Promise<UserCollection> {
        const url = this.parser.url('/v1/users', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'start_cursor': startCursor,
                'page_size': pageSize,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as UserCollection;
        }

        const statusCode = response.status;
        if (statusCode >= 0 && statusCode <= 999) {
            throw new ErrorException(await response.json() as Error);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Retrieves a User using the ID specified.
     *
     * @returns {Promise<User>}
     * @throws {ErrorException}
     * @throws {ClientException}
     */
    public async get(userId: string): Promise<User> {
        const url = this.parser.url('/v1/users/:user_id', {
            'user_id': userId,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as User;
        }

        const statusCode = response.status;
        if (statusCode >= 0 && statusCode <= 999) {
            throw new ErrorException(await response.json() as Error);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
