/**
 * UserCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {User} from "./User";
export interface UserCollection {
    results?: Array<User>
    next_cursor?: string
    has_more?: boolean
}
