/**
 * User automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Person} from "./Person";
export interface User {
    object?: string
    id?: string
    type?: string
    person?: Person
    name?: string
    avatar_url?: string
}
